import type { Product, Category, Order } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Oversized', slug: 'oversized', description: 'Relaxed, dropped-shoulder fits — premium cotton, boxy silhouettes.', itemCount: 32 },
];

export interface Collection {
  id: string;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  banner: string;
  thumbnail: string;
  productCount: number;
  tag?: string;
  categoryIds: number[];
}

export const COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Oversized Fits',
    slug: 'oversized',
    description: 'Boxy, relaxed silhouettes for the streetwear-forward man.',
    longDescription: 'Drop the shoulders. Embrace the drape. Our Oversized Fits collection is built for those who move through the world with ease — premium 240 GSM cotton, boxy cuts, and lengths that fall just right.',
    banner: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=1400&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    productCount: 18,
    tag: 'Trending',
    categoryIds: [1],
  },
  {
    id: 'col-2',
    name: 'Classic Essentials',
    slug: 'classic',
    description: 'Timeless everyday basics built to last.',
    longDescription: 'The foundation of every wardrobe. Our Classic Essentials are cut clean, woven tight, and finished to outlast every trend. Plain, polo, and everything in between.',
    banner: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1400&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    productCount: 24,
    categoryIds: [3, 4],
  },
  {
    id: 'col-3',
    name: 'Graphic Series',
    slug: 'graphic',
    description: 'Bold prints and artistic statements.',
    longDescription: 'Art on fabric. The Graphic Series collaborates with independent artists to bring you limited-run prints on premium tees. Each drop is unique — once it\'s gone, it\'s gone.',
    banner: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=1400&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80',
    productCount: 12,
    tag: 'New',
    categoryIds: [2],
  },
  {
    id: 'col-4',
    name: 'Premium Collection',
    slug: 'premium',
    description: 'Luxe fabrics — Pima cotton, modal blends, and more.',
    longDescription: 'For those who know the difference. The Premium Collection uses only the finest Pima cotton and modal blends — softer, stronger, and noticeably better. Wear it and feel it.',
    banner: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=1400&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80',
    productCount: 9,
    tag: 'Luxury',
    categoryIds: [5],
  },
  {
    id: 'col-5',
    name: 'Summer Edit',
    slug: 'summer',
    description: 'Light, breathable picks for the hot season.',
    longDescription: 'Stay cool without compromising style. The Summer Edit brings you the lightest, most breathable tees — perfect for beach days, city strolls, or just sweating less.',
    banner: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1400&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80',
    productCount: 7,
    categoryIds: [1, 2, 3],
  },
];

export function getCollectionBySlug(slug: string): Collection | undefined {
  return COLLECTIONS.find((c) => c.slug === slug);
}

export function getProductsForCollection(collection: Collection): Product[] {
  return MOCK_PRODUCTS.filter((p) => collection.categoryIds.includes(p.category_id));
}



const COLORS = [
  { name: 'Black', hex: '#111111' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Charcoal', hex: '#4a4a4a' },
  { name: 'Olive', hex: '#6B6B40' },
  { name: 'Navy', hex: '#1B2A4A' },
  { name: 'Brown', hex: '#5C3D2E' },
  { name: 'Off-White', hex: '#F5F0E8' },
  { name: 'Grey', hex: '#9E9E9E' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    product_id: 'p1',
    sku: 'SB-OVR-BLK-L',
    name: 'Shadow Black Oversized T-Shirt',
    slug: 'shadow-black-oversized',
    description: 'Premium 240 GSM cotton with a relaxed oversized fit. Perfect for everyday wear. Features dropped shoulders and a boxy silhouette for that effortless streetwear look.',
    price: 1299,
    discount_price: 899,
    category_id: 1,
    category: CATEGORIES[0],
    status: 'active',
    color: 'Black',
    colors: [COLORS[0], COLORS[2], COLORS[4], COLORS[5], COLORS[7]],
    fabric: '100% Cotton',
    weight: 240,
    fit_type: 'oversized',
    stock_quantity: 45,
    is_in_stock: true,
    tags: ['oversized', 'cotton', 'casual', 'streetwear'],
    rating: 4.8,
    review_count: 256,
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', alt: 'Shadow Black Front', type: 'image' },
      { url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', alt: 'Shadow Black Side', type: 'image' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800', alt: 'Shadow Black Detail', type: 'image' },
    ],
    variants: [
      { variant_id: 'v1-s', product_id: 'p1', sku: 'SB-S', color: 'Black', size: 'S', stock_quantity: 10 },
      { variant_id: 'v1-m', product_id: 'p1', sku: 'SB-M', color: 'Black', size: 'M', stock_quantity: 15 },
      { variant_id: 'v1-l', product_id: 'p1', sku: 'SB-L', color: 'Black', size: 'L', stock_quantity: 12 },
      { variant_id: 'v1-xl', product_id: 'p1', sku: 'SB-XL', color: 'Black', size: 'XL', stock_quantity: 8 },
    ],
  },
  {
    product_id: 'p2',
    sku: 'MB-OVR-BRN-L',
    name: 'Mocha Brown Oversized T-Shirt',
    slug: 'mocha-brown-oversized',
    description: 'Earth-toned oversized tee crafted from premium cotton blend. Soft, breathable, and incredibly comfortable for all-day wear.',
    price: 1299,
    discount_price: 899,
    category_id: 1,
    category: CATEGORIES[0],
    status: 'active',
    color: 'Brown',
    colors: [COLORS[5], COLORS[0], COLORS[2]],
    fabric: '100% Cotton',
    weight: 240,
    fit_type: 'oversized',
    stock_quantity: 32,
    is_in_stock: true,
    tags: ['oversized', 'cotton', 'earth-tone'],
    rating: 4.7,
    review_count: 183,
    images: [
      { url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800', alt: 'Mocha Brown Front', type: 'image' },
      { url: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4f7e?w=800', alt: 'Mocha Brown Side', type: 'image' },
    ],
    variants: [
      { variant_id: 'v2-s', product_id: 'p2', sku: 'MB-S', color: 'Brown', size: 'S', stock_quantity: 8 },
      { variant_id: 'v2-m', product_id: 'p2', sku: 'MB-M', color: 'Brown', size: 'M', stock_quantity: 12 },
      { variant_id: 'v2-l', product_id: 'p2', sku: 'MB-L', color: 'Brown', size: 'L', stock_quantity: 7 },
      { variant_id: 'v2-xl', product_id: 'p2', sku: 'MB-XL', color: 'Brown', size: 'XL', stock_quantity: 5 },
    ],
  },
  {
    product_id: 'p3',
    sku: 'VG-OVR-GRY-L',
    name: 'Vintage Grey Oversized T-Shirt',
    slug: 'vintage-grey-oversized',
    description: 'Washed grey oversized tee with vintage character. Garment-dyed for a lived-in feel. Gets better with every wash.',
    price: 1299,
    discount_price: 899,
    category_id: 1,
    category: CATEGORIES[0],
    status: 'active',
    color: 'Grey',
    colors: [COLORS[7], COLORS[0], COLORS[6]],
    fabric: '100% Cotton',
    weight: 220,
    fit_type: 'oversized',
    stock_quantity: 28,
    is_in_stock: true,
    tags: ['oversized', 'vintage', 'washed'],
    rating: 4.6,
    review_count: 142,
    images: [
      { url: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800', alt: 'Vintage Grey Front', type: 'image' },
    ],
    variants: [
      { variant_id: 'v3-m', product_id: 'p3', sku: 'VG-M', color: 'Grey', size: 'M', stock_quantity: 10 },
      { variant_id: 'v3-l', product_id: 'p3', sku: 'VG-L', color: 'Grey', size: 'L', stock_quantity: 10 },
      { variant_id: 'v3-xl', product_id: 'p3', sku: 'VG-XL', color: 'Grey', size: 'XL', stock_quantity: 8 },
    ],
  },
  {
    product_id: 'p4',
    sku: 'OW-OVR-WHT-L',
    name: 'Off White Oversized T-Shirt',
    slug: 'off-white-oversized',
    description: 'Clean off-white oversized essential. A wardrobe staple made from 100% combed cotton for ultimate softness.',
    price: 1299,
    discount_price: 899,
    category_id: 1,
    category: CATEGORIES[0],
    status: 'active',
    color: 'Off-White',
    colors: [COLORS[6], COLORS[0], COLORS[7]],
    fabric: '100% Combed Cotton',
    weight: 240,
    fit_type: 'oversized',
    stock_quantity: 40,
    is_in_stock: true,
    tags: ['oversized', 'minimal', 'essential'],
    rating: 4.9,
    review_count: 312,
    images: [
      { url: 'https://images.unsplash.com/photo-1622445275576-721325763afe?w=800', alt: 'Off White Front', type: 'image' },
    ],
    variants: [
      { variant_id: 'v4-s', product_id: 'p4', sku: 'OW-S', color: 'Off-White', size: 'S', stock_quantity: 12 },
      { variant_id: 'v4-m', product_id: 'p4', sku: 'OW-M', color: 'Off-White', size: 'M', stock_quantity: 15 },
      { variant_id: 'v4-l', product_id: 'p4', sku: 'OW-L', color: 'Off-White', size: 'L', stock_quantity: 10 },
      { variant_id: 'v4-xl', product_id: 'p4', sku: 'OW-XL', color: 'Off-White', size: 'XL', stock_quantity: 3 },
    ],
  },
  {
    product_id: 'p5',
    sku: 'MB-PRM-BLK-L',
    name: 'Midnight Black Premium Tee',
    slug: 'midnight-black-premium',
    description: 'Our flagship premium tee crafted from 260 GSM Pima cotton. Luxuriously soft with superior colour retention.',
    price: 1999,
    discount_price: 1499,
    category_id: 5,
    category: CATEGORIES[4],
    status: 'active',
    color: 'Black',
    colors: [COLORS[0], COLORS[1], COLORS[2]],
    fabric: 'Pima Cotton',
    weight: 260,
    fit_type: 'relaxed',
    stock_quantity: 20,
    is_in_stock: true,
    tags: ['premium', 'pima cotton', 'luxury'],
    rating: 4.9,
    review_count: 89,
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800', alt: 'Midnight Black Premium', type: 'image' },
    ],
    variants: [
      { variant_id: 'v5-m', product_id: 'p5', sku: 'MBP-M', color: 'Black', size: 'M', stock_quantity: 8 },
      { variant_id: 'v5-l', product_id: 'p5', sku: 'MBP-L', color: 'Black', size: 'L', stock_quantity: 7 },
      { variant_id: 'v5-xl', product_id: 'p5', sku: 'MBP-XL', color: 'Black', size: 'XL', stock_quantity: 5 },
    ],
  },
  {
    product_id: 'p6',
    sku: 'PL-PLN-OLV-M',
    name: 'Classic Polo Olive',
    slug: 'classic-polo-olive',
    description: 'Refined polo crafted from premium piqué cotton. A timeless style that transitions from casual to smart-casual effortlessly.',
    price: 1699,
    discount_price: 1299,
    category_id: 4,
    category: CATEGORIES[3],
    status: 'active',
    color: 'Olive',
    colors: [COLORS[4], COLORS[0], COLORS[6]],
    fabric: 'Piqué Cotton',
    weight: 220,
    fit_type: 'regular',
    stock_quantity: 25,
    is_in_stock: true,
    tags: ['polo', 'smart-casual', 'classic'],
    rating: 4.7,
    review_count: 67,
    images: [
      { url: 'https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=800', alt: 'Classic Polo Olive', type: 'image' },
    ],
    variants: [
      { variant_id: 'v6-m', product_id: 'p6', sku: 'PL-M', color: 'Olive', size: 'M', stock_quantity: 10 },
      { variant_id: 'v6-l', product_id: 'p6', sku: 'PL-L', color: 'Olive', size: 'L', stock_quantity: 10 },
      { variant_id: 'v6-xl', product_id: 'p6', sku: 'PL-XL', color: 'Olive', size: 'XL', stock_quantity: 5 },
    ],
  },
  {
    product_id: 'p7',
    sku: 'GR-GFX-BLK-M',
    name: 'Urban Reflections Graphic Tee',
    slug: 'urban-reflections-graphic',
    description: 'Bold graphic print on premium 200 GSM cotton. Screen-printed artwork that lasts wash after wash. Express your style.',
    price: 1099,
    discount_price: 799,
    category_id: 2,
    category: CATEGORIES[1],
    status: 'active',
    color: 'Black',
    colors: [COLORS[0], COLORS[6]],
    fabric: '100% Cotton',
    weight: 200,
    fit_type: 'regular',
    stock_quantity: 35,
    is_in_stock: true,
    tags: ['graphic', 'streetwear', 'art'],
    rating: 4.5,
    review_count: 124,
    images: [
      { url: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800', alt: 'Urban Reflections Graphic', type: 'image' },
    ],
    variants: [
      { variant_id: 'v7-s', product_id: 'p7', sku: 'GR-S', color: 'Black', size: 'S', stock_quantity: 8 },
      { variant_id: 'v7-m', product_id: 'p7', sku: 'GR-M', color: 'Black', size: 'M', stock_quantity: 15 },
      { variant_id: 'v7-l', product_id: 'p7', sku: 'GR-L', color: 'Black', size: 'L', stock_quantity: 12 },
    ],
  },
  {
    product_id: 'p8',
    sku: 'NV-PLN-NVY-M',
    name: 'Navy Essential Plain Tee',
    slug: 'navy-essential-plain',
    description: 'The ultimate everyday plain tee. Super soft 180 GSM jersey cotton. Slim fit that flatters without constricting.',
    price: 899,
    discount_price: 699,
    category_id: 3,
    category: CATEGORIES[2],
    status: 'active',
    color: 'Navy',
    colors: [COLORS[4], COLORS[0], COLORS[1], COLORS[7]],
    fabric: '100% Cotton Jersey',
    weight: 180,
    fit_type: 'slim',
    stock_quantity: 60,
    is_in_stock: true,
    tags: ['plain', 'essential', 'slim-fit', 'everyday'],
    rating: 4.6,
    review_count: 278,
    images: [
      { url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800', alt: 'Navy Essential', type: 'image' },
    ],
    variants: [
      { variant_id: 'v8-s', product_id: 'p8', sku: 'NV-S', color: 'Navy', size: 'S', stock_quantity: 15 },
      { variant_id: 'v8-m', product_id: 'p8', sku: 'NV-M', color: 'Navy', size: 'M', stock_quantity: 20 },
      { variant_id: 'v8-l', product_id: 'p8', sku: 'NV-L', color: 'Navy', size: 'L', stock_quantity: 15 },
      { variant_id: 'v8-xl', product_id: 'p8', sku: 'NV-XL', color: 'Navy', size: 'XL', stock_quantity: 10 },
    ],
  },
];

export const getFeaturedProducts = () => MOCK_PRODUCTS.slice(0, 4);
export const getProductBySlug = (slug: string) =>
  MOCK_PRODUCTS.find((p) => p.slug === slug);
export const getProductsByCategory = (categorySlug: string) =>
  MOCK_PRODUCTS.filter((p) => p.category?.slug === categorySlug);
export const getBestSellers = () =>
  [...MOCK_PRODUCTS].sort((a, b) => (b.review_count ?? 0) - (a.review_count ?? 0)).slice(0, 4);

// ─── Mock Orders ──────────────────────────────────────────────────────────────
export const MOCK_ORDERS: Order[] = [
  {
    order_id: 'ord-001',
    order_number: 'TXN-2026-8821',
    user_id: 'u1',
    items: [
      {
        product: MOCK_PRODUCTS[0],
        variant: MOCK_PRODUCTS[0].variants![1],
        quantity: 2,
        unit_price: 899,
      },
    ],
    status: 'delivered',
    payment_method: 'upi',
    payment_status: 'paid',
    shipping_address: {
      address_id: 'addr-1',
      full_name: 'Demo User',
      phone: '+91 98765 43210',
      address_line_1: '42 Koramangala 4th Block',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
      country: 'India',
      is_default: true,
    },
    subtotal: 1798,
    discount: 200,
    shipping: 0,
    tax: 0,
    total: 1598,
    coupon_code: 'FIRST10',
    created_at: '2026-05-20T10:30:00Z',
    updated_at: '2026-05-24T16:00:00Z',
  },
  {
    order_id: 'ord-002',
    order_number: 'TXN-2026-9104',
    user_id: 'u1',
    items: [
      {
        product: MOCK_PRODUCTS[3],
        variant: MOCK_PRODUCTS[3].variants![2],
        quantity: 1,
        unit_price: MOCK_PRODUCTS[3].discount_price ?? MOCK_PRODUCTS[3].price,
      },
      {
        product: MOCK_PRODUCTS[6],
        variant: MOCK_PRODUCTS[6].variants![1],
        quantity: 1,
        unit_price: MOCK_PRODUCTS[6].discount_price ?? MOCK_PRODUCTS[6].price,
      },
    ],
    status: 'shipped',
    payment_method: 'card',
    payment_status: 'paid',
    shipping_address: {
      address_id: 'addr-1',
      full_name: 'Demo User',
      phone: '+91 98765 43210',
      address_line_1: '42 Koramangala 4th Block',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
      country: 'India',
      is_default: true,
    },
    subtotal: (MOCK_PRODUCTS[3].discount_price ?? MOCK_PRODUCTS[3].price) + (MOCK_PRODUCTS[6].discount_price ?? MOCK_PRODUCTS[6].price),
    discount: 0,
    shipping: 0,
    tax: 0,
    total: (MOCK_PRODUCTS[3].discount_price ?? MOCK_PRODUCTS[3].price) + (MOCK_PRODUCTS[6].discount_price ?? MOCK_PRODUCTS[6].price),
    created_at: '2026-06-08T14:20:00Z',
    updated_at: '2026-06-10T09:15:00Z',
  },
  {
    order_id: 'ord-003',
    order_number: 'TXN-2026-9312',
    user_id: 'u1',
    items: [
      {
        product: MOCK_PRODUCTS[1],
        variant: MOCK_PRODUCTS[1].variants![1],
        quantity: 1,
        unit_price: 899,
      },
    ],
    status: 'confirmed',
    payment_method: 'cod',
    payment_status: 'pending',
    shipping_address: {
      address_id: 'addr-1',
      full_name: 'Demo User',
      phone: '+91 98765 43210',
      address_line_1: '42 Koramangala 4th Block',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
      country: 'India',
      is_default: true,
    },
    subtotal: 899,
    discount: 0,
    shipping: 79,
    tax: 0,
    total: 978,
    created_at: '2026-06-11T18:45:00Z',
    updated_at: '2026-06-12T08:00:00Z',
  },
];
